on:
  release:
    types: [created]
    

jobs:

  build:
    strategy:
      matrix:
        goos: [darwin, linux]
        goarch: [386, amd64]

    name: Release artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
        id: go

      - name: Check out code into the Go module directory
      - uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Compile and package
        run: |
          GOOS=${{matrix.goos}} GOARCH=${{matrix.goarch}} go build -v -o clarify && tar cfz clarify_${{matrix.goos}}_${{matrix.goarch}}.tar.gz clarify

      - name: Upload package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./clarify_${{matrix.goos}}_${{matrix.goarch}}.tar.gz
          asset_name: clarify_${{matrix.goos}}_${{matrix.goarch}}.tar.gz
          asset_content_type: application/gzip
          
